version: "3.9"
services:
  postgres:
    image: postgres:alpine3.17
    environment:
      - POSTGRES_DB=simple_bank
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  redis:
    image: redis:alpine3.17
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1026:8080"
      - "1027:9090"
    environment:
      - DB_SOURCE=postgresql://root:admin@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]

volumes:
  postgres-volume:
